version: "3.7"

services:
  nginx:
    build:
      context: docker/dev/nginx
    ports:
      - "${PORT}:80"
    volumes:
      - ./app:/app
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker
      dockerfile: dev/php-fpm/Dockerfile
    volumes:
      - ./app:/app
